botswana7:
  test_ratio: 0.2
  validation_ratio: 0.1
  delimiter: " "
  min_input_length: 12
  max_input_length: 24
  test_input_length: 24
  test_prediction_length: 6
  batch_size: 2048
  device: cuda
  max_epochs: 10
  block_size: 40
  learning_rate: 1.e-3
  weight_decay: 5.e-3
  beta1: 0.9
  beta2: 0.95
  grad_clip: 1.0
  decay_lr: True
  warmup_iters: 100
  lr_decay_iters: 10000
  min_lr: 5.e-8
  seed: 42
  data_dir: ../
  dataset: botswana7
  n_layer: 12
  n_head: 4
  n_embd: 512
  bias: False
  dropout: 0
  model_checkpoint_directory: ./models/
  train_from_checkpoint_if_exist: False
  custom_initialization: False
  patience: 3