kenya7:
  test_ratio: 0.2
  validation_ratio: 0.1
  delimiter: " "
  min_input_length: 10
  max_input_length: 14
  test_input_length: 10
  test_prediction_length: 5
  batch_size: 256
  device: mps
  max_epochs: 10
  block_size: 24
  learning_rate: 5.e-4
  weight_decay: 5.e-3
  beta1: 0.9
  beta2: 0.95
  grad_clip: 1.0
  decay_lr: True
  warmup_iters: 100
  lr_decay_iters: 10000
  min_lr: 5.e-8
  seed: 42
  data_dir: ./data
  dataset: kenya7
  n_layer: 12
  n_head: 4
  n_embd: 512
  bias: False
  dropout: 0
  model_checkpoint_directory: ./models/
  train_from_checkpoint_if_exist: False
  custom_initialization: False
  patience: 3